import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
// Components
import Banner from '../components/banner';
import Card from '../components/card';
// 
import { fetchCoffeeStore } from '../lib/coffee-store';

export async function getStaticProps(context) {
    console.log("hi getStaticProps");

    const coffeeStores = await fetchCoffeeStore();

    return {
        props: {
            coffeeStores,
        }, // will be passed tot he page component as props
    }
}


export default function Home(props) {
    console.log("props", props);

    const handleONBannerBtnClick = () => {
        console.log("hi banner button");
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Coffee Connisseur</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>

            <main className={styles.main}>
                <Banner buttonText="View stores nearby" handleOnClick={handleONBannerBtnClick} />
                <div className={styles.heroImage}>
                    <Image src="/static/hero-image.png" width={700} height={300} alt="Hero Image" />
                </div>

                {props.coffeeStores.length > 0 && (
                    <div>
                        <h2 className={styles.heading2}>Houston stores</h2>
                        <div className={styles.cardLayout}>
                            {props.coffeeStores.map((coffeeStore) => {
                                return (
                                    <Card
                                        key={coffeeStore.fsq_id}
                                        name={coffeeStore.name}
                                        imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                                        href={`/coffee-store/${coffeeStore.fsq_id}`}
                                        className={styles.card}
                                    />
                                );
                            })}
                        </div>
                    </div>
                )}
            </main>


        </div>
    )
}